version: "3.7"
services:
  keycloak:
    container_name: keycloak
    env_file:
      - .env
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    ports:
      - 9001:8080
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: keycloak
    volumes:
      - ./keycloak-data:/opt/keycloak/data/
    restart: always
    command: [ "start-dev" ]
    depends_on:
      - postgres

  postgres:
    container_name: keycloak_db
    env_file:
      - .env
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "keycloak" ]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql