version: '3.8'
services:

  postgres:
    image: postgres:16.1
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=p@ssw0rd
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data

  keycloak:
    build: .
    image: keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=p@ssw0rd
      - KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.keycloak.events:DEBUG
    command: 
      - start-dev
      - --import-realm
    depends_on:
      - postgres
    volumes:
      - ./realms:/opt/keycloak/data/import