version: '3.8'
services:

  postgres:
    image: postgres:16.1
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=p@ssw0rd
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data

  keycloak:
    build: .
    image: keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=p@ssw0rd
      - KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.keycloak.events:DEBUG
    command: 
      - start-dev
      - --import-realm
    depends_on:
      - postgres
    volumes:
      - ./realms:/opt/keycloak/data/import
  # keycloak2:
  #   image: quay.io/keycloak/keycloak:24.0.3
  #   container_name: keycloak2
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #     - KC_DB=postgres
  #     - KC_DB_URL_HOST=postgres
  #     - KC_DB_URL_DATABASE=keycloak
  #     - KC_DB_USERNAME=keycloak
  #     - KC_DB_PASSWORD=password
  #     - KC_CACHE=ispn
  #     - KC_HOSTNAME=keycloak-cluster.lb
  #     - KC_PROXY_HEADERS=xforwarded
  #     - KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.keycloak.events:DEBUG
  #   command: start-dev
  #   depends_on:
  #     - postgres

  # nginx:
  #   image: nginx:1.25.4
  #   container_name: nginx
  #   hostname: keycloak-cluster.lb
  #   volumes:
  #     - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - keycloak1
  #     - keycloak2